### ISSUE TITLE
Find HTML 5 Theme

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/KhCE#4]
Find beautiful HTML 5 template for Front-End.

**Comment by rajaramdhukhwa** [comment]
Its my selection khCE of themes links...
http://demo.wpzoom.com/academica-pro/
http://wrapbootstrap.com/preview/WB0NSRT37
http://wrapbootstrap.com/preview/WB0F65379

**Comment by ErSKS** [comment]
@rajaramdhukhwa Browse more HTML 5 themes.

**Comment by rajaramdhukhwa** [comment]
Thank you sir...

**Comment by rajaramdhukhwa** [comment]
snapshots of KhCE web templates
![responsive website tem_ - https___themes 3rdwavemedia com_college-green_1 6 1_](https://user-images.githubusercontent.com/30016516/27992700-f59645f4-64b9-11e7-998d-f0212ccb8907.png)
![responsive website template fo_ - https___themes 3rdwavemedia com_academy_1 1_](https://user-images.githubusercontent.com/30016516/27992719-4334efe0-64ba-11e7-946f-2ed49035a2ef.png)
