### ISSUE TITLE
Need Chairman's Message

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/KhCE#45]
Update Chairman's Message

**Comment by ErSKS** [comment]
# Message from the Chairman
On behalf the college family, it is my pleasure to welcome you at Khwopa College of Engineering (KhCE). I hope you will spend your valuable time to know about our mission and goals.
People of Bhaktapur had a dream of at least one graduate per family and ultimately intellectualizing the whole society. To realize this dream Khwopa Engineering College, Khwopa College of Engineering, Khwopa Secondary School, Khwopa College and Khwopa Polytechnic Institute were established. People's Representatives along with People of Bhaktapur had worked hard to establish these institutes and progress to this level. These are totally community-based pioneer efforts by the Bhaktapur Municipality in the field of education. First of all, I would like to express my deepest gratitude to people of Bhaktapur and their representatives for their untiring efforts. 
Our effort in KhCE is not only making the students competent in their professional field but also to make a civilized and patriotic citizen. Since its establishment in the year 2008 A.D., KhCE is providing quality education at the affordable fee. Backed by the people of Bhaktapur and dedicated faculties and staff KhCE is continuously progressing in engineering education and gained the national and international reputation. Similarly, the honesty and excellence shown by the students from Khwopa in any field give the feeling of satisfaction and pride to us and they have continuously been maintaining this spirit till date.  
The college is equipped with adequate infrastructures to achieve the quality education. Reinforced by our excellent academic result and hard-won glory of Bhaktapur we are aspiring to establish Khwopa University. Upon establishment of the University, we will focus on education linked with the productive labor.
Bhaktapur Municipality will continue to accomplish its responsibility to provide higher education people of common economic strata. For this, we will continue our effort on adding new academic programs enhancing the research excellence in the areas suitable for local national and international issues. 
Together we creatively address the issues and look for innovative approaches to meet the needs and desires of the students. Finally, I hope you will consider KhCE as a place where your talents can be honed and you can prepare yourself for a rewarding career in your interested field of engineering and eventually to be morally honored and cultured citizen.
Thank you
Sunil Prajapati
Chairman

**Comment by ErSKS** [comment]
Done !

**Comment by sunil9176** [comment]
In the homepage chairman's message is just seen as ...more. I think it should be corrected. In the detail message the spacing and font needs to be reviewed because it looks very lengthy.

**Comment by ErSKS** [comment]
Ok Sir !
