### ISSUE TITLE
Add new Banner - Block-E Photo

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/KhCE#48]
Add E-Block Building's Photo in Banner

**Comment by ErSKS** [comment]
HQ Full Photo:
![khce - banner_lg](https://user-images.githubusercontent.com/5508421/29115685-350696f0-7d18-11e7-937c-09fc15ec2c9f.jpg)

**Comment by ErSKS** [comment]
It is hard to add in our rectangular banner.

**Comment by ErSKS** [comment]
![khce](https://user-images.githubusercontent.com/5508421/29116075-7062477a-7d19-11e7-8087-0628366337fe.jpg)

**Comment by sunil9176** [comment]
I think its better to put only three buildings. This does not look good. we
can put this photo some where else, may be gallery.

*Sunil Duwal*
*(Msc. Hydrology, hydrogeology and Water Resource, Stockholm University)*
Principal
Khwopa College of Engineering(Affiliated to Tribhuwan University)
Bhaktapur Municipality, Ward No.:02, Libali
P.O.Box: 84; Fax: +977-1-5122202
Office Phone: +977-1-5122098,+977-1-5122201 / 109(Ext.)
Mobile: +977-9851139795
E-mail: duwal.sunil@khwopa.edu.np / duwal.sunil@gmail.com
Skype: sunil9176
URL: www.khwopa.edu.np

*~~~~~~~~~*Enthusiasm moves the world. -Arthur Balfour ~~~~~~~~~~

**Comment by ErSKS** [comment]
Ok Sir !

**Comment by ErSKS** [comment]
Is this photo ok for our banner?
![be_electrical](https://user-images.githubusercontent.com/5508421/29153229-0f435e14-7dac-11e7-9519-24b6a477cb5c.jpg)

**Comment by sunil9176** [comment]
Yes this is ok! add if there is similar photo for civil as well.

**Comment by ErSKS** [comment]
@shyambasukala Shyam Sir, we need same angled photo of Civil Engineering Department too.
