### ISSUE TITLE
Add Photos to Gallery

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/KhCE#54]
Add More Photos to KhCE Gallery

**Comment by ErSKS** [comment]
Surveying 
![img_3451](https://user-images.githubusercontent.com/5508421/29160467-0e2c3cdc-7dd2-11e7-9148-da9686fa221c.JPG)

**Comment by ErSKS** [comment]
Student at Electronics Lab
![img_3595](https://user-images.githubusercontent.com/5508421/29160546-66117444-7dd2-11e7-87c3-178e78b74e14.JPG)

**Comment by ErSKS** [comment]
2 Photos Added !

**Comment by sunil9176** [comment]
Caption being wrong for the last two photographs.


http://khwopa.edu.np/entrance/photo_gallery

*Sunil Duwal*
*(Msc. Hydrology, hydrogeology and Water Resource, Stockholm University)*
Principal
Khwopa College of Engineering(Affiliated to Tribhuwan University)
Bhaktapur Municipality, Ward No.:02, Libali
P.O.Box: 84; Fax: +977-1-5122202
Office Phone: +977-1-5122098,+977-1-5122201 / 109(Ext.)
Mobile: +977-9851139795
E-mail: duwal.sunil@khwopa.edu.np / duwal.sunil@gmail.com
Skype: sunil9176
URL: www.khwopa.edu.np

*~~~~~~~~~*Enthusiasm moves the world. -Arthur Balfour ~~~~~~~~~~

**Comment by ErSKS** [comment]
Title of last two images of entrance gallery are changed !
