### ISSUE TITLE
OAFS Summary

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/KhCE#89]
# OAFS v1.0 Summary
![00 oafs v1 0 summary](https://user-images.githubusercontent.com/5508421/29502419-a2a735c6-864f-11e7-8c81-b953b4bcc63c.png)

**Comment by ErSKS** [comment]
# OAFS v2.0 Summary
![00 oafs v2 0 summary](https://user-images.githubusercontent.com/5508421/29502426-b705d86a-864f-11e7-9fe4-5baa543f7dad.png)

**Comment by ErSKS** [comment]
# OAFS v3.0 Summary
![00 oafs v3 0 summary](https://user-images.githubusercontent.com/5508421/29502436-c85415d2-864f-11e7-8cd4-aee5d7f00832.png)

**Comment by sunil9176** [comment]
v3 needs change in a number 1 more student applied just now

**Comment by ErSKS** [comment]
**OAFS v3.0 Summary**
![00 oafs v3 0 summary](https://user-images.githubusercontent.com/5508421/29604739-34568404-8808-11e7-8968-208ca11a0b1a.png)
